const data = [
    {
        movieTitle: "Price and Prejudice",
        movieDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, corrupti illum, est laboriosam labore non quibusdam praesentium dolores velit adipisci tenetur? Molestiae, similique. Impedit error quod maiores at temporibus inventore, laboriosam sapiente, ea a modi veniam? Ab, vero nisi dolor numquam in, ipsa blanditiis cum doloremque praesentium alias quidem laborum ducimus quod similique harum illum a natus! Suscipit modi provident itaque, numquam illo exercitationem quo harum, ipsam earum qui eos. Hic molestiae soluta eum quaerat consequatur impedit error, numquam minima culpa suscipit doloremque tempora explicabo a. Aliquid iste culpa ullam aperiam aliquam qui numquam, illum iure commodi quae et facere nisi vero consequatur odio perspiciatis molestias ea. Nulla necessitatibus tempore doloremque officia placeat sint, totam voluptatem quo veritatis nesciunt eos iusto quaerat beatae quae dolorum sunt, non veniam nisi suscipit rem esse deleniti ipsam quis! Aut eum doloremque facilis quod nemo laboriosam! Maiores cupiditate excepturi, laborum odio officia dicta ipsam dolor fugit quibusdam vero saepe optio voluptates voluptas est velit? Impedit corrupti et vel perferendis reprehenderit nemo repudiandae fugiat accusamus minima! Necessitatibus aspernatur ducimus est dolor, voluptas magni porro, veritatis maiores unde sed, nulla ipsum nihil voluptates expedita quam officia quibusdam nemo illo totam tempora! Hic cupiditate nobis nisi fugit nulla, harum voluptatibus dignissimos quis quo optio culpa ut quidem quod maxime consequuntur modi quibusdam error iusto? Modi voluptatibus ipsam quas iste, atque ea sint aut quis veritatis magni nihil sed sunt, mollitia molestiae explicabo a! Deleniti beatae soluta nulla voluptates nam molestias, doloribus quas, praesentium molestiae delectus, provident eum!",
        movieDirector: "Joe Wright",
        movieImage: "https://www.usmagazine.com/wp-content/uploads/2022/10/Pride-and-Prejudice-2005-Cast-Where-Are-They-Now-Feature.jpg?quality=86&strip=all",
        movieRating: 4.5
    },
    {
        movieTitle: "Lord of the Rings",
        movieDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, corrupti illum, est laboriosam labore non quibusdam praesentium dolores velit adipisci tenetur? Molestiae, similique. Impedit error quod maiores at temporibus inventore, laboriosam sapiente, ea a modi veniam? Ab, vero nisi dolor numquam in, ipsa blanditiis cum doloremque praesentium alias quidem laborum ducimus quod similique harum illum a natus! Suscipit modi provident itaque, numquam illo exercitationem quo harum, ipsam earum qui eos. Hic molestiae soluta eum quaerat consequatur impedit error, numquam minima culpa suscipit doloremque tempora explicabo a. Aliquid iste culpa ullam aperiam aliquam qui numquam, illum iure commodi quae et facere nisi vero consequatur odio perspiciatis molestias ea. Nulla necessitatibus tempore doloremque officia placeat sint, totam voluptatem quo veritatis nesciunt eos iusto quaerat beatae quae dolorum sunt, non veniam nisi suscipit rem esse deleniti ipsam quis! Aut eum doloremque facilis quod nemo laboriosam! Maiores cupiditate excepturi, laborum odio officia dicta ipsam dolor fugit quibusdam vero saepe optio voluptates voluptas est velit? Impedit corrupti et vel perferendis reprehenderit nemo repudiandae fugiat accusamus minima! Necessitatibus aspernatur ducimus est dolor, voluptas magni porro, veritatis maiores unde sed, nulla ipsum nihil voluptates expedita quam officia quibusdam nemo illo totam tempora! Hic cupiditate nobis nisi fugit nulla, harum voluptatibus dignissimos quis quo optio culpa ut quidem quod maxime consequuntur modi quibusdam error iusto? Modi voluptatibus ipsam quas iste, atque ea sint aut quis veritatis magni nihil sed sunt, mollitia molestiae explicabo a! Deleniti beatae soluta nulla voluptates nam molestias, doloribus quas, praesentium molestiae delectus, provident eum!",
        movieDirector: "Peter Jackson",
        movieImage: "https://qph.cf2.quoracdn.net/main-qimg-a55fa4c296b41b0654f7d257862f9953",
        movieRating: 4.5
    },
    {
        movieTitle: "The Dark Knight",
        movieDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, corrupti illum, est laboriosam labore non quibusdam praesentium dolores velit adipisci tenetur? Molestiae, similique. Impedit error quod maiores at temporibus inventore, laboriosam sapiente, ea a modi veniam? Ab, vero nisi dolor numquam in, ipsa blanditiis cum doloremque praesentium alias quidem laborum ducimus quod similique harum illum a natus! Suscipit modi provident itaque, numquam illo exercitationem quo harum, ipsam earum qui eos. Hic molestiae soluta eum quaerat consequatur impedit error, numquam minima culpa suscipit doloremque tempora explicabo a. Aliquid iste culpa ullam aperiam aliquam qui numquam, illum iure commodi quae et facere nisi vero consequatur odio perspiciatis molestias ea. Nulla necessitatibus tempore doloremque officia placeat sint, totam voluptatem quo veritatis nesciunt eos iusto quaerat beatae quae dolorum sunt, non veniam nisi suscipit rem esse deleniti ipsam quis! Aut eum doloremque facilis quod nemo laboriosam! Maiores cupiditate excepturi, laborum odio officia dicta ipsam dolor fugit quibusdam vero saepe optio voluptates voluptas est velit? Impedit corrupti et vel perferendis reprehenderit nemo repudiandae fugiat accusamus minima! Necessitatibus aspernatur ducimus est dolor, voluptas magni porro, veritatis maiores unde sed, nulla ipsum nihil voluptates expedita quam officia quibusdam nemo illo totam tempora! Hic cupiditate nobis nisi fugit nulla, harum voluptatibus dignissimos quis quo optio culpa ut quidem quod maxime consequuntur modi quibusdam error iusto? Modi voluptatibus ipsam quas iste, atque ea sint aut quis veritatis magni nihil sed sunt, mollitia molestiae explicabo a! Deleniti beatae soluta nulla voluptates nam molestias, doloribus quas, praesentium molestiae delectus, provident eum!",
        movieDirector: "Christopher Nolan",
        movieImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5UdW_3o3KgBPBhd_UjVQnHrpmx8kMAGs8nRNtfSfr9Q&s",
        movieRating: 4.5
    },
    {
        movieTitle: "The Shawshank Redemption",
        movieDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, corrupti illum, est laboriosam labore non quibusdam praesentium dolores velit adipisci tenetur? Molestiae, similique. Impedit error quod maiores at temporibus inventore, laboriosam sapiente, ea a modi veniam? Ab, vero nisi dolor numquam in, ipsa blanditiis cum doloremque praesentium alias quidem laborum ducimus quod similique harum illum a natus! Suscipit modi provident itaque, numquam illo exercitationem quo harum, ipsam earum qui eos. Hic molestiae soluta eum quaerat consequatur impedit error, numquam minima culpa suscipit doloremque tempora explicabo a. Aliquid iste culpa ullam aperiam aliquam qui numquam, illum iure commodi quae et facere nisi vero consequatur odio perspiciatis molestias ea. Nulla necessitatibus tempore doloremque officia placeat sint, totam voluptatem quo veritatis nesciunt eos iusto quaerat beatae quae dolorum sunt, non veniam nisi suscipit rem esse deleniti ipsam quis! Aut eum doloremque facilis quod nemo laboriosam! Maiores cupiditate excepturi, laborum odio officia dicta ipsam dolor fugit quibusdam vero saepe optio voluptates voluptas est velit? Impedit corrupti et vel perferendis reprehenderit nemo repudiandae fugiat accusamus minima! Necessitatibus aspernatur ducimus est dolor, voluptas magni porro, veritatis maiores unde sed, nulla ipsum nihil voluptates expedita quam officia quibusdam nemo illo totam tempora! Hic cupiditate nobis nisi fugit nulla, harum voluptatibus dignissimos quis quo optio culpa ut quidem quod maxime consequuntur modi quibusdam error iusto? Modi voluptatibus ipsam quas iste, atque ea sint aut quis veritatis magni nihil sed sunt, mollitia molestiae explicabo a! Deleniti beatae soluta nulla voluptates nam molestias, doloribus quas, praesentium molestiae delectus, provident eum!",
        movieDirector: "Frank Darabont",
        movieImage: "https://i.scdn.co/image/ab67616d0000b273e710c1f5b228046932790031",
        movieRating: 4.5
    },
]

export { data }